version: "3"
services:
  db:
    image: questdb/questdb
    container_name: questdb
    restart: always
    volumes:
      - /home/quest:/var/lib/questdb
    ports:
      - "9000:9000"

  app:
    image: qtdx
    container_name: qtdx
    environment:
      - WORK_DIR=/tmp/tdx
      - DB_HOST=db
    command: ["sleep", "infinity"]
    volumes:
      - /datapool/tdx:/tmp/tdx
    depends_on:
      - db
