services:
  db:
    image: questdb/questdb
    container_name: questdb
    restart: always
    network_mode: host
    volumes:
      - /home/quest:/var/lib/questdb
  app:
    image: tdxq
    container_name: tdxq
    restart: always
    network_mode: host
    environment:
      - WORK_DIR=/tmp/tdx
      - QW_TOKEN=984f1f40
      - DB_HOST=localhost
    command: ["sleep", "infinity"]
    volumes:
      - /datapool/tdx:/tmp
